[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "alabaster",
    "attrs",
    "coincidence",
    "coverage",
    "coverage_pyver_pragma",
    "docutils",
    "domdf_python_tools",
    "github",
    "importlib_metadata",
    "jinja2",
    "markupsafe",
    "mypy",
    "prettyprinter",
    "pytest",
    "pytest_benchmark",
    "pytest_cov",
    "pytest_mypy_plugins",
    "pytest_mypy_plugins_shim",
    "pytest_randomly",
    "pytest_rerunfailures",
    "pytest_timeout",
    "requests",
    "sdjson",
    "setuptools",
    "snapshottest",
    "sphinx_toolbox",
    "sphinxcontrib_applehelp",
    "sphinxcontrib_devhelp",
    "sphinxcontrib_htmlhelp",
    "sphinxcontrib_jsmath",
    "sphinxcontrib_qthelp",
    "sphinxcontrib_serializinghtml",
    "sphobjinv",
    "toolz",
    "typing_extensions",
    "typing_inspect",
]
known_first_party = [ "attr_utils",]
